title: RadianceOS Project
description: The documentation of the RadianceOS project.
theme: just-the-docs

url: https://radianceos-project.github.io/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
