title: RadianceOS Project
description: The documentation of the RadianceOS project.
theme: just-the-docs

url: https://radianceos-project.github.io/

aux_links:
  2.0 Docs: /2.0/docs/
  1.0 Docs: /1.0/docs/
